# Generated by Django 3.0.8 on 2020-07-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fournisseur_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(max_length=50),
        ),
    ]
